#!/bin/bash
# Archive one-off documents with clear archive headers

ARCHIVE_DIR="/Users/davidtowne/Desktop/Coding/codebase/docs/archive/one-offs"
mkdir -p "$ARCHIVE_DIR"

# List of one-off documents to archive
FILES=(
  "docs/status/GENERAL_STATUS_STEP_4_MIGRATION_STATUS.md"
  "docs/status/GENERAL_GUIDE_STEPS_4_5_COMPLETION_SUMMARY.md"
  "docs/status/GENERAL_GUIDE_STEP_6_OPEN-SOURCE_ENHANCEMENTS_-_COMPLETION_SUMMA.md"
  "docs/status/GENERAL_GUIDE_STEP_8_RAG_PIPELINE_-_COMPLETION_SUMMARY.md"
  "docs/status/GENERAL_STATUS_STEP_13_FILE_COMPARISON_REPORT.md"
  "docs/status/GENERAL_STATUS_STEP_13_RECONCILIATION_STATUS_CHECK.md"
  "docs/status/GENERAL_STATUS_STEP_17_TEST_EXECUTION_STATUS.md"
  "docs/status/CYRANO_STATUS_STEP_17_COMPLETION_REPORT_MCP_COMPLIANCE_TESTING.md"
  "docs/status/GENERAL_GUIDE_STEP_17_COMPLETE_-_SUMMARY_FOR_USER.md"
  "docs/status/GENERAL_API_STEP_5_COMPLETION_SUMMARY_REPLACE_DUMMY_CODE_AND_M.md"
  "docs/status/GENERAL_STATUS_PRIMARY_AGENT_STATUS_REPORT.md"
  "docs/status/GENERAL_STATUS_MANAGING_AGENT_STATUS.md"
  "docs/status/GENERAL_STATUS_STATUS_INDICATORUPDATER_AGENT.md"
  "docs/status/GENERAL_STATUS_INSTRUCTIONS_FOR_STATUS_INDICATORUPDATER_AGENT.md"
  "docs/status/GENERAL_STATUS_PRE-AUDIT_REPORT_CODE_REVIEW_AND_ISSUE_IDENTIFICAT.md"
  "docs/status/GENERAL_STATUS_FOCUSED_PRE-AUDIT_REPORT_COMPREHENSIVE_CODE_REVIEW.md"
  "docs/status/GENERAL_STATUS_PRE-UPLOAD_STATUS_REPORT.md"
  "docs/status/CYRANO_STATUS_CYRANO_PROJECT_REALISTIC_STATUS_ASSESSMENT.md"
  "docs/status/CYRANO_STATUS_CYRANO_PROJECT_CORRECTED_STATUS_ASSESSMENT.md"
  "docs/status/CYRANO_STATUS_CYRANO_MCP_SERVER_SECURITY_ASSESSMENT_REPORT.md"
  "docs/status/GENERAL_STATUS_PRIORITIZED_TASKS_COMPLETION_REPORT.md"
  "docs/status/LEXFIAT_STATUS_LEXFIAT_STATUS.md"
  "docs/status/CYRANO_STATUS_CYRANO_RECONCILIATION_DIFF_REPORT.md"
  "docs/status/GENERAL_STATUS_ERROR_REPORT_MISCONFIGURATION_TROUBLESHOOTING_LOG.md"
  "docs/guides/LEXFIAT_GUIDE_LEXFIAT_DEVELOPER_HANDOFF_DOCUMENTATION.md"
  "docs/guides/LEXFIAT_GUIDE_LEXFIAT_PACKAGE_SUMMARY_FOR_DEVELOPER_TRANSFER.md"
  "docs/guides/GENERAL_GUIDE_COMPLETE_PROJECT_TRANSFER_MANIFEST.md"
  "docs/guides/GENERAL_GUIDE_COSMOS_TRANSFER_PACKAGE.md"
  "docs/guides/GENERAL_GUIDE_SWIMMEET_TRANSFER_PACKAGE_-_COMPLETE_DOCUMENTATION.md"
  "docs/guides/GENERAL_GUIDE_SWIMMEET_AI_ORCHESTRATION_PLATFORM_-_TRANSFER_PACK.md"
  "docs/guides/GENERAL_GUIDE_TRANSFER_PACKAGE_CHECKLIST.md"
  "docs/guides/GENERAL_GUIDE_PRIMARY_AGENT_HANDOFF_SUMMARY.md"
  "docs/guides/LEXFIAT_GUIDE_LEXFIAT_DEVELOPMENT_SESSION_SUMMARY.md"
  "docs/guides/LEXFIAT_GUIDE_LEXFIAT_DASHBOARD_IMPLEMENTATION_SUMMARY.md"
  "docs/guides/GENERAL_GUIDE_WORK_COMPLETED_-_2025-11-26.md"
  "docs/guides/GENERAL_GUIDE_STEPS_4_5_COMPLETION_2025-11-26.md"
  "docs/guides/GENERAL_GUIDE_HOUSEKEEPING_WORK_SUMMARY.md"
  "docs/guides/GENERAL_GUIDE_COPILOT_WORK_ASSESSMENT.md"
  "docs/guides/GENERAL_GUIDE_AUTONOMOUS_WORK_PLAN_-_NEXT_6_HOURS.md"
  "docs/guides/GENERAL_GUIDE_STEP_13_RECONCILIATION_PLAN.md"
  "docs/guides/GENERAL_GUIDE_STEP_13_REMAINING_FILES_TO_REVIEW.md"
  "docs/guides/GENERAL_GUIDE_PRE-AUDIT_ISSUES_WORKFLOW_ASSIGNMENT_RECOMMENDATIO.md"
  "docs/guides/GENERAL_GUIDE_ISOLATED_DOCUMENTS_FOR_REVIEW.md"
  "docs/guides/GENERAL_GUIDE_NOT_USEFUL_-_TECHNICALLY_ACCURATE_BUT_PROVIDES_NO_.md"
  "docs/guides/GENERAL_GUIDE_BILLING_DISPUTE_CONVERSATION_-_REPLIT_AI_AGENT_FAI.md"
  "docs/guides/GENERAL_GUIDE_TIME_WASTE_CALCULATION_-_REPLIT_AI_AGENT_FAILURES.md"
  "docs/ui/UI_UI_UI_DEMO_STATUS.md"
  "docs/ui/LEXFIAT_UI_LEXFIAT_UI_ENHANCEMENTS_SUMMARY.md"
  "docs/DOCUMENTATION_ANALYSIS_REPORT.md"
  "docs/DOCUMENTATION_REORGANIZATION_SUMMARY.md"
)

BASE_DIR="/Users/davidtowne/Desktop/Coding/codebase"

for file in "${FILES[@]}"; do
  full_path="$BASE_DIR/$file"
  if [ -f "$full_path" ]; then
    filename=$(basename "$file")
    archive_path="$ARCHIVE_DIR/ARCHIVED_${filename}"
    
    # Add archive header to file
    {
      echo "---"
      echo "⚠️ ARCHIVED DOCUMENT - INACTIVE"
      echo ""
      echo "This document has been archived as a one-off/historical record."
      echo "For current project status, see: docs/PROJECT_CHANGE_LOG.md"
      echo "Archived: 2025-11-28"
      echo "---"
      echo ""
      cat "$full_path"
    } > "$archive_path"
    
    # Remove original
    rm "$full_path"
    echo "Archived: $file"
  fi
done

echo "Archive complete. Files moved to: $ARCHIVE_DIR"

