---
# Codacy configuration (disable PMD analyzers by omission)
engines:
  eslint:
    enabled: true
  eslint-typescript:
    enabled: true
  jest:
    enabled: true
  shellcheck:
    enabled: true
  metrics:
    enabled: true

# Exclude common generated/vendor/archived directories
exclude_paths:
  - 'node_modules/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/coverage/**'
  - '**/public/**'
  - 'Legacy/**'
  - 'Cyrano/**'
  - 'apps/**'
  - 'LexFiat/**'
  - 'docs/**'
  - 'Miscellaneous/**'

# Patterns to skip for analysis
exclude_patterns:
  - '**/*.min.js'
  - '**/*.bundle.js'
  - '**/*.spec.ts'
  - '**/*.test.ts'
