# Codacy configuration with disabled problematic analyzers
engines:
  eslint:
    enabled: true
    exclude_paths:
      - 'Legacy/**'
      - 'Cyrano/**'
      - 'apps/**'
      - 'LexFiat/**'
      - 'docs/**'
      - 'node_modules/**'
  eslint-typescript:
    enabled: true
    exclude_paths:
      - 'Legacy/**'
      - 'Cyrano/**'
      - 'apps/**'
      - 'LexFiat/**'
      - 'docs/**'
      - 'node_modules/**'
  jest:
    enabled: true
  pmd: 
    enabled: false
  pmd-legacy:
    enabled: false

# Exclude common generated and vendor directories to reduce noise
exclude_paths:
  - 'node_modules/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/coverage/**'
  - '**/public/**'
  - 'Legacy/**'
  - 'Cyrano/**'
  - 'apps/**'
  - 'LexFiat/**'
  - 'docs/**'
  - 'Miscellaneous/**'

# Patterns to skip for analysis
patterns:
  - '**/*.min.js'
  - '**/*.bundle.js'
  - '**/*.spec.ts'
  - '**/*.test.ts'
