---
# Codacy configuration with explicitly disabled PMD analyzers
# This repository is TypeScript/React based and does not contain Java code
engines:
  # Explicitly disable PMD analyzers (no Java code in repository)
  pmd:
    enabled: false
  pmd-legacy:
    enabled: false
  # Enable JavaScript/TypeScript analyzers
  eslint:
    enabled: true
  eslint-typescript:
    enabled: true
  jest:
    enabled: true
  shellcheck:
    enabled: true
  metrics:
    enabled: true

# Exclude common generated/vendor/archived directories
exclude_paths:
  - 'node_modules/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/coverage/**'
  - '**/public/**'
  - 'Legacy/**'
  - 'Miscellaneous/**'
  - '.cursor/**'

# Patterns to skip for analysis
exclude_patterns:
  - '**/*.min.js'
  - '**/*.bundle.js'
  - '**/*.spec.ts'
  - '**/*.test.ts'
