---
# Codacy configuration with disabled problematic analyzers
# Explicitly disable PMD analyzers to prevent configuration errors
# This repository is TypeScript/React based and does not contain Java code
engines:
  # Disable PMD analyzers (Java-specific, causes "No rules found" errors)
  pmd:
    enabled: false
  pmd-legacy:
    enabled: false
  # Enable JavaScript/TypeScript analyzers
  eslint:
    enabled: true
  eslint-typescript:
    enabled: true
  jest:
    enabled: true
  # Enable documentation and shell script analyzers
  shellcheck:
    enabled: true
  remark-lint:
    enabled: true
  # Enable metrics
  metrics:
    enabled: true

# Exclude common generated/vendor/archived directories
exclude_paths:
  - 'node_modules/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/coverage/**'
  - '**/public/**'
  - 'Legacy/**'
  - 'Miscellaneous/**'
  - '.cursor/**'

# Patterns to skip for analysis
exclude_patterns:
  - '**/*.min.js'
  - '**/*.bundle.js'
  - '**/*.spec.ts'
  - '**/*.test.ts'
