import { Link } from 'react-router-dom';
import { FileText, Scale, TrendingUp, AlertTriangle, Building2 } from 'lucide-react';

export default function HomePage() {
  return (
    <div className="space-y-8">
      <div className="text-center">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">
          Welcome to LexFiat Forecaster<sup className="text-xs">™</sup>
        </h1>
        <p className="text-xl text-gray-600 mb-8">
          Generate hypothetical forecasts for tax returns, child support, and QDROs
        </p>
        <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 mb-8 max-w-3xl mx-auto">
          <div className="flex">
            <AlertTriangle className="h-5 w-5 text-yellow-400 mr-2" />
            <div className="text-left">
              <p className="text-sm text-yellow-700">
                <strong>Important:</strong> All forecasts generated by LexFiat Forecaster<sup>™</sup> are
                hypothetical and not filing-ready. They must be reviewed and finalized by qualified
                professionals before any filing or use in legal proceedings.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="grid md:grid-cols-4 gap-6">
        <Link
          to="/tax"
          className="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition-shadow"
        >
          <FileText className="h-12 w-12 text-blue-600 mx-auto mb-4" />
          <h2 className="text-xl font-semibold text-gray-900 mb-2">Tax Return Forecast</h2>
          <p className="text-gray-600">
            Generate hypothetical tax return forecasts using IRS forms and calculations
          </p>
        </Link>

        <Link
          to="/city-tax"
          className="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition-shadow"
        >
          <Building2 className="h-12 w-12 text-orange-600 mx-auto mb-4" />
          <h2 className="text-xl font-semibold text-gray-900 mb-2">City Tax (Testing)</h2>
          <p className="text-gray-600">Forecast city income taxes for Lansing and Albion (scaffold)</p>
        </Link>

        <Link
          to="/support"
          className="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition-shadow"
        >
          <Scale className="h-12 w-12 text-green-600 mx-auto mb-4" />
          <h2 className="text-xl font-semibold text-gray-900 mb-2">Child Support Forecast</h2>
          <p className="text-gray-600">
            Calculate hypothetical child support scenarios using state-specific formulas
          </p>
        </Link>

        <Link
          to="/qdro"
          className="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition-shadow"
        >
          <TrendingUp className="h-12 w-12 text-purple-600 mx-auto mb-4" />
          <h2 className="text-xl font-semibold text-gray-900 mb-2">QDRO Forecast</h2>
          <p className="text-gray-600">
            Generate hypothetical QDRO division scenarios with ERISA compliance
          </p>
        </Link>
      </div>
    </div>
  );

}